matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - config/.wordlist-hl7au.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - 'au-fhir-base/pages/_includes/*-intro.md'
  - 'au-fhir-base/pages/_includes/downloads.md'
  - 'au-fhir-base/pages/_includes/extensions.md'
  - 'au-fhir-base/pages/_includes/guidance.md'
  - 'au-fhir-base/pages/_includes/history.md'
  - 'au-fhir-base/pages/_includes/intro.md'
  - 'au-fhir-base/pages/_includes/profiles.md'  
  - 'au-fhir-base/pages/_includes/terminology.md'  
  default_encoding: utf-8
