name: Validate hl7au/au-fhir-base resource profiles - metadata
on: push

jobs:
  build:
    name: validate au-fhir-base resource profiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone and checkout hl7au/au-fhir-base repo
        uses: actions/checkout@v3
        with:
          repository: hl7au/au-fhir-base
          path: au-fhir-base
          
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Download FHIR validator
        run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator.jar

      - name: Validate StructureDefinition resources, against the meta StructureDefinition profile that checks metadata
        run: java -jar validator.jar -version 4.0.1 au-fhir-base/input/resources/au-*.xml -ig https://robstwd.github.io/fhir-ig-experiment-01/package.tgz -profile "https://about.me/robeastwood/fhir/ig/StructureDefinition/structuredefinition-hl7au-sdf-1"
