name: Validate hl7au/au-fhir-core resource profiles - core spec
on: push

jobs:
  build:
    name: validate au-fhir-core resource profiles
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone and checkout hl7au/au-fhir-base repo
        uses: actions/checkout@v3
        with:
          repository: hl7au/au-fhir-core
          path: au-fhir-core
          
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Download FHIR validator
        run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar -O validator.jar

      - name: Validate StructureDefinition resources, against core FHIRVersion 4.0.1
        run: java -jar validator.jar -version 4.0.1 au-fhir-core/input/resources/au-*.xml
